// <auto-generated />
using KursPortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KursPortal.Migrations
{
    [DbContext(typeof(KursPortalDbContext))]
    [Migration("20261008092538_OnlyKursMigration1")]
    partial class OnlyKursMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KursPortal.Models.Kurs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AnzahlTeilnehmer")
                        .HasColumnType("int");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DauerInTagen")
                        .HasColumnType("int");

                    b.Property<string>("Dozent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inhalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KursName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kurse");
                });
#pragma warning restore 612, 618
        }
    }
}
